# project name
spring.application.name=SpringSecurutyProject

## use ur own credentials => if diabled, defined own UserDetails configs


# --- Database Connection ---


# --- JPA / Hibernate Settings ---
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
